<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The ArticleBean class maps the 'article' table in database.
 * @dbTable article
 *
 */
class ArticleBean extends ArticleBaseBean 
{

}