<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The DiaporamaBean class maps the 'diaporama' table in database.
 * @dbTable diaporama
 *
 */
class DiaporamaBean extends DiaporamaBaseBean 
{

}