<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The ModeleArticleBean class maps the 'modele_article' table in database.
 * @dbTable modele_article
 *
 */
class ModeleArticleBean extends ModeleArticleBaseBean 
{

}