<?php
namespace coiffuresenegal\Dao\Bean;

use Database\TDBM\TDBMObject;


/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the ModeleArticleBean class instead!
 */

/**
 * The ModeleArticleBaseBean class maps the 'modele_article' table in database.
 * @dbTable modele_article
 */
class ModeleArticleBaseBean extends TDBMObject
{
	/**
	 * The getter for the "id_modele" column.
	 *
	 * @dbType int
	 * @dbColumn id_modele
	 * @return string
	 */
	public function getIdModele(){
		return $this->__get('id_modele');
	}
	
	/**
	 * The setter for the "id_modele" column.
	 *
	 * @dbColumn id_modele
	 * @param string $id_modele
	 */
	public function setIdModele($id_modele) {
		$this->__set('id_modele', $id_modele);
	}
	
	/**
	 * The getter for the "nom_modele" column.
	 *
	 * @dbType string
	 * @dbColumn nom_modele
	 * @return string
	 */
	public function getNomModele(){
		return $this->__get('nom_modele');
	}
	
	/**
	 * The setter for the "nom_modele" column.
	 *
	 * @dbColumn nom_modele
	 * @param string $nom_modele
	 */
	public function setNomModele($nom_modele) {
		$this->__set('nom_modele', $nom_modele);
	}
	
	/**
	 * The getter for the "image" column.
	 *
	 * @dbType string
	 * @dbColumn image
	 * @return string
	 */
	public function getImage(){
		return $this->__get('image');
	}
	
	/**
	 * The setter for the "image" column.
	 *
	 * @dbColumn image
	 * @param string $image
	 */
	public function setImage($image) {
		$this->__set('image', $image);
	}
	
	/**
	 * The getter for the "actif" column.
	 *
	 * @dbType int
	 * @dbColumn actif
	 * @return string
	 */
	public function getActif(){
		return $this->__get('actif');
	}
	
	/**
	 * The setter for the "actif" column.
	 *
	 * @dbColumn actif
	 * @param string $actif
	 */
	public function setActif($actif) {
		$this->__set('actif', $actif);
	}
	
	/**
	 * The getter for the "created_at" column.
	 * It is returned as a PHP timestamp.
	 *
	 * @dbType datetime
	 * @dbColumn created_at
	 * @return timestamp
	 */
	public function getCreatedAt(){
		$date = $this->__get('created_at');
		if($date === null)
			return null;
		else
			return strtotime($date);
	}
	
	/**
	 * The setter for the "created_at" column.
	 * It must be provided as a PHP timestamp.
	 *
	 * @dbColumn created_at
	 * @param timestamp $created_at
	 */
	public function setCreatedAt($created_at) {
		if($created_at === null)
			$this->__set('created_at', null);
		else
			$this->__set('created_at', date("Y-m-d H:i:s", $created_at));
	}
	
	/**
	 * The getter for the "updated_at" column.
	 * It is returned as a PHP timestamp.
	 *
	 * @dbType timestamp
	 * @dbColumn updated_at
	 * @return timestamp
	 */
	public function getUpdatedAt(){
		$date = $this->__get('updated_at');
		if($date === null)
			return null;
		else
			return strtotime($date);
	}
	
	/**
	 * The setter for the "updated_at" column.
	 * It must be provided as a PHP timestamp.
	 *
	 * @dbColumn updated_at
	 * @param timestamp $updated_at
	 */
	public function setUpdatedAt($updated_at) {
		if($updated_at === null)
			$this->__set('updated_at', null);
		else
			$this->__set('updated_at', date("Y-m-d H:i:s", $updated_at));
	}
	
}
?>