<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The PhotoBean class maps the 'photo' table in database.
 * @dbTable photo
 *
 */
class PhotoBean extends PhotoBaseBean 
{

}