<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The RegionBean class maps the 'region' table in database.
 * @dbTable region
 *
 */
class RegionBean extends RegionBaseBean 
{

}