<?php
namespace coiffuresenegal\Dao\Bean;

use Database\TDBM\TDBMObject;

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the RegionBean class instead!
 */

/**
 * The RegionBaseBean class maps the 'region' table in database.
 * @dbTable region
 */
class RegionBaseBean extends TDBMObject
{
	/**
	 * The getter for the "id_region" column.
	 *
	 * @dbType int
	 * @dbColumn id_region
	 * @return string
	 */
	public function getIDRegion(){
		return $this->__get('id_region');
	}
	
	/**
	 * The setter for the "id_region" column.
	 *
	 * @dbColumn id_region
	 * @param string $id_region
	 */
	public function setIDRegion($id_region) {
		$this->__set('id_region', $id_region);
	}
	
	/**
	 * The getter for the "nom_region" column.
	 *
	 * @dbType string
	 * @dbColumn nom_region
	 * @return string
	 */
	public function getNomRegion(){
		return $this->__get('nom_region');
	}
	
	/**
	 * The setter for the "nom_region" column.
	 *
	 * @dbColumn nom_region
	 * @param string $nom_region
	 */
	public function setNomRegion($nom_region) {
		$this->__set('nom_region', $nom_region);
	}
	
	/**
	 * The getter for the "image" column.
	 *
	 * @dbType string
	 * @dbColumn image
	 * @return string
	 */
	public function getImage(){
		return $this->__get('image');
	}
	
	/**
	 * The setter for the "image" column.
	 *
	 * @dbColumn image
	 * @param string $image
	 */
	public function setImage($image) {
		$this->__set('image', $image);
	}
	
	/**
	 * The getter for the "banniere" column.
	 *
	 * @dbType string
	 * @dbColumn banniere
	 * @return string
	 */
	public function getBanniere(){
		return $this->__get('banniere');
	}
	
	/**
	 * The setter for the "banniere" column.
	 *
	 * @dbColumn banniere
	 * @param string $banniere
	 */
	public function setBanniere($banniere) {
		$this->__set('banniere', $banniere);
	}
	
	/**
	 * The getter for the "notice" column.
	 *
	 * @dbType string
	 * @dbColumn notice
	 * @return string
	 */
	public function getNotice(){
		return $this->__get('notice');
	}
	
	/**
	 * The setter for the "notice" column.
	 *
	 * @dbColumn notice
	 * @param string $notice
	 */
	public function setNotice($notice) {
		$this->__set('notice', $notice);
	}
	
	/**
	 * The getter for the "presentation" column.
	 *
	 * @dbType string
	 * @dbColumn presentation
	 * @return string
	 */
	public function getPresentation(){
		return $this->__get('presentation');
	}
	
	/**
	 * The setter for the "presentation" column.
	 *
	 * @dbColumn presentation
	 * @param string $presentation
	 */
	public function setPresentation($presentation) {
		$this->__set('presentation', $presentation);
	}
	
	/**
	 * The getter for the "position" column.
	 *
	 * @dbType int
	 * @dbColumn position
	 * @return string
	 */
	public function getPosition(){
		return $this->__get('position');
	}
	
	/**
	 * The setter for the "position" column.
	 *
	 * @dbColumn position
	 * @param string $position
	 */
	public function setPosition($position) {
		$this->__set('position', $position);
	}
	
	/**
	 * The getter for the "actif" column.
	 *
	 * @dbType int
	 * @dbColumn actif
	 * @return string
	 */
	public function getActif(){
		return $this->__get('actif');
	}
	
	/**
	 * The setter for the "actif" column.
	 *
	 * @dbColumn actif
	 * @param string $actif
	 */
	public function setActif($actif) {
		$this->__set('actif', $actif);
	}
	
	/**
	 * The getter for the "tag" column.
	 *
	 * @dbType string
	 * @dbColumn tag
	 * @return string
	 */
	public function getTag(){
		return $this->__get('tag');
	}
	
	/**
	 * The setter for the "tag" column.
	 *
	 * @dbColumn tag
	 * @param string $tag
	 */
	public function setTag($tag) {
		$this->__set('tag', $tag);
	}
	
	/**
	 * The getter for the "created_at" column.
	 * It is returned as a PHP timestamp.
	 *
	 * @dbType datetime
	 * @dbColumn created_at
	 * @return timestamp
	 */
	public function getCreatedAt(){
		$date = $this->__get('created_at');
		if($date === null)
			return null;
		else
			return strtotime($date);
	}
	
	/**
	 * The setter for the "created_at" column.
	 * It must be provided as a PHP timestamp.
	 *
	 * @dbColumn created_at
	 * @param timestamp $created_at
	 */
	public function setCreatedAt($created_at) {
		if($created_at === null)
			$this->__set('created_at', null);
		else
			$this->__set('created_at', date("Y-m-d H:i:s", $created_at));
	}
	
	/**
	 * The getter for the "updated_at" column.
	 * It is returned as a PHP timestamp.
	 *
	 * @dbType timestamp
	 * @dbColumn updated_at
	 * @return timestamp
	 */
	public function getUpdatedAt(){
		$date = $this->__get('updated_at');
		if($date === null)
			return null;
		else
			return strtotime($date);
	}
	
	/**
	 * The setter for the "updated_at" column.
	 * It must be provided as a PHP timestamp.
	 *
	 * @dbColumn updated_at
	 * @param timestamp $updated_at
	 */
	public function setUpdatedAt($updated_at) {
		if($updated_at === null)
			$this->__set('updated_at', null);
		else
			$this->__set('updated_at', date("Y-m-d H:i:s", $updated_at));
	}
	
}
?>