<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The SalonUneRegionBean class maps the 'salon_une_region' table in database.
 * @dbTable salon_une_region
 *
 */
class SalonUneRegionBean extends SalonUneRegionBaseBean 
{

}