<?php
namespace coiffuresenegal\Dao\Bean;

use Database\TDBM\TDBMObject;

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the SalonBean class instead!
 */

/**
 * The SalonBaseBean class maps the 'salon' table in database.
 * @dbTable salon
 */
class SalonBaseBean extends TDBMObject
{
	/**
	 * The getter for the "id_salon" column.
	 *
	 * @dbType int
	 * @dbColumn id_salon
	 * @return string
	 */
	public function getIdSalon(){
		return $this->__get('id_salon');
	}
	
	/**
	 * The setter for the "id_salon" column.
	 *
	 * @dbColumn id_salon
	 * @param string $id_salon
	 */
	public function setIdSalon($id_salon) {
		$this->__set('id_salon', $id_salon);
	}
	
	/**
	 * The getter for the "id_ville" column.
	 *
	 * @dbType int
	 * @dbColumn id_ville
	 * @return string
	 */
	public function getIdVille(){
		return $this->__get('id_ville');
	}
	
	/**
	 * The setter for the "id_ville" column.
	 *
	 * @dbColumn id_ville
	 * @param string $id_ville
	 */
	public function setIdVille($id_ville) {
		$this->__set('id_ville', $id_ville);
	}
	
	/**
	 * The getter for the "nom_salon" column.
	 *
	 * @dbType string
	 * @dbColumn nom_salon
	 * @return string
	 */
	public function getNomSalon(){
		return $this->__get('nom_salon');
	}
	
	/**
	 * The setter for the "nom_salon" column.
	 *
	 * @dbColumn nom_salon
	 * @param string $nom_salon
	 */
	public function setNomSalon($nom_salon) {
		$this->__set('nom_salon', $nom_salon);
	}
	
	/**
	 * The getter for the "image" column.
	 *
	 * @dbType string
	 * @dbColumn image
	 * @return string
	 */
	public function getImage(){
		return $this->__get('image');
	}
	
	/**
	 * The setter for the "image" column.
	 *
	 * @dbColumn image
	 * @param string $image
	 */
	public function setImage($image) {
		$this->__set('image', $image);
	}
	
	/**
	 * The getter for the "banniere" column.
	 *
	 * @dbType string
	 * @dbColumn banniere
	 * @return string
	 */
	public function getBanniere(){
		return $this->__get('banniere');
	}
	
	/**
	 * The setter for the "banniere" column.
	 *
	 * @dbColumn banniere
	 * @param string $banniere
	 */
	public function setBanniere($banniere) {
		$this->__set('banniere', $banniere);
	}
	
	/**
	 * The getter for the "notice" column.
	 *
	 * @dbType string
	 * @dbColumn notice
	 * @return string
	 */
	public function getNotice(){
		return $this->__get('notice');
	}
	
	/**
	 * The setter for the "notice" column.
	 *
	 * @dbColumn notice
	 * @param string $notice
	 */
	public function setNotice($notice) {
		$this->__set('notice', $notice);
	}
	
	/**
	 * The getter for the "presentation" column.
	 *
	 * @dbType string
	 * @dbColumn presentation
	 * @return string
	 */
	public function getPresentation(){
		return $this->__get('presentation');
	}
	
	/**
	 * The setter for the "presentation" column.
	 *
	 * @dbColumn presentation
	 * @param string $presentation
	 */
	public function setPresentation($presentation) {
		$this->__set('presentation', $presentation);
	}
	
	/**
	 * The getter for the "position" column.
	 *
	 * @dbType int
	 * @dbColumn position
	 * @return string
	 */
	public function getPosition(){
		return $this->__get('position');
	}
	
	/**
	 * The setter for the "position" column.
	 *
	 * @dbColumn position
	 * @param string $position
	 */
	public function setPosition($position) {
		$this->__set('position', $position);
	}
	
	/**
	 * The getter for the "actif" column.
	 *
	 * @dbType int
	 * @dbColumn actif
	 * @return string
	 */
	public function getActif(){
		return $this->__get('actif');
	}
	
	/**
	 * The setter for the "actif" column.
	 *
	 * @dbColumn actif
	 * @param string $actif
	 */
	public function setActif($actif) {
		$this->__set('actif', $actif);
	}
	
	/**
	 * The getter for the "tag" column.
	 *
	 * @dbType string
	 * @dbColumn tag
	 * @return string
	 */
	public function getTag(){
		return $this->__get('tag');
	}
	
	/**
	 * The setter for the "tag" column.
	 *
	 * @dbColumn tag
	 * @param string $tag
	 */
	public function setTag($tag) {
		$this->__set('tag', $tag);
	}
	
	/**
	 * The getter for the "created_at" column.
	 * It is returned as a PHP timestamp.
	 *
	 * @dbType datetime
	 * @dbColumn created_at
	 * @return timestamp
	 */
	public function getCreatedAt(){
		$date = $this->__get('created_at');
		if($date === null)
			return null;
		else
			return strtotime($date);
	}
	
	/**
	 * The setter for the "created_at" column.
	 * It must be provided as a PHP timestamp.
	 *
	 * @dbColumn created_at
	 * @param timestamp $created_at
	 */
	public function setCreatedAt($created_at) {
		if($created_at === null)
			$this->__set('created_at', null);
		else
			$this->__set('created_at', date("Y-m-d H:i:s", $created_at));
	}
	
	/**
	 * The getter for the "updated_at" column.
	 * It is returned as a PHP timestamp.
	 *
	 * @dbType timestamp
	 * @dbColumn updated_at
	 * @return timestamp
	 */
	public function getUpdatedAt(){
		$date = $this->__get('updated_at');
		if($date === null)
			return null;
		else
			return strtotime($date);
	}
	
	/**
	 * The setter for the "updated_at" column.
	 * It must be provided as a PHP timestamp.
	 *
	 * @dbColumn updated_at
	 * @param timestamp $updated_at
	 */
	public function setUpdatedAt($updated_at) {
		if($updated_at === null)
			$this->__set('updated_at', null);
		else
			$this->__set('updated_at', date("Y-m-d H:i:s", $updated_at));
	}
	
}
?>