<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The SalonUneVilleBean class maps the 'salon_une_ville' table in database.
 * @dbTable salon_une_ville
 *
 */
class SalonUneVilleBean extends SalonUneVilleBaseBean 
{

}