<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The SalonBean class maps the 'salon' table in database.
 * @dbTable salon
 *
 */
class SalonBean extends SalonBaseBean 
{

}