<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The UserAdminBean class maps the 'user_admin' table in database.
 * @dbTable user_admin
 *
 */
class UserAdminBean extends UserAdminBaseBean 
{

}