<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Dao\Bean;
 
/**
 * The VilleBean class maps the 'ville' table in database.
 * @dbTable ville
 *
 */
class VilleBean extends VilleBaseBean 
{

}