<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The ArticleDao class will maintain the persistance of coiffuresenegal\Dao\Bean\ArticleBean class into the article table.
 *
 * @Component
 * @dbTable article
 */
class ArticleDao extends ArticleDaoBase
{

}