<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The DiaporamaDao class will maintain the persistance of coiffuresenegal\Dao\Bean\DiaporamaBean class into the diaporama table.
 *
 * @Component
 * @dbTable diaporama
 */
class DiaporamaDao extends DiaporamaDaoBase
{

}