<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The ModeleArticleDao class will maintain the persistance of coiffuresenegal\Dao\Bean\ModeleArticleBean class into the modele_article table.
 *
 * @Component
 * @dbTable modele_article
 */
class ModeleArticleDao extends ModeleArticleDaoBase
{

}