<?php

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the PhotoDao class instead!
 */

namespace coiffuresenegal\Dao;

use Database\TDBM\TDBMService;

/**
 * The PhotoDaoBase class will maintain the persistance of coiffuresenegal\Dao\Bean\PhotoBean class into the photo table.
 * 
 */
class PhotoDaoBase extends DaoCommon implements DAOInterface {

    public $tableName = "photo";
    public $tablePrimaryKey = "ID_photo";
    public $tableColumns = array(
        'ID_photo',
        'ID_article',
        'ID_diaporama',
        'notice',
        'image',
        'position',
        'created_at',
        'updated_at'
    );
    
    
    /**
     * @var TDBMService
     */
    protected $tdbmService;

    public function __construct() {
        $this->setTdbmService(new TDBMService());
    }
    
    /**
     * Sets the TDBM service used by this DAO.
     *
     * @Property
     * @Compulsory
     * @param TDBMService $tdbmService
     */
    public function setTdbmService(TDBMService $tdbmService) {
        $this->tdbmService = $tdbmService;
    }

    /**
	 * Return a new instance of coiffuresenegal\Dao\Bean\PhotoBean object, that will be persisted in database.
	 *
	 * @return coiffuresenegal\Dao\Bean\PhotoBean
	 */
	public function create() {
		return $this->tdbmService->getNewObject('photo', true, 'coiffuresenegal\Dao\Bean\PhotoBean');
	}
	
	/**
	 * Persist the coiffuresenegal\Dao\Bean\PhotoBean instance
	 *
	 */
	public function save($obj) {
		$obj->save();
	}

	/**
	 * Get all Photo records. 
	 *
	 * @return array<coiffuresenegal\Dao\Bean\PhotoBean>
	 */
	public function getList() {
		return $this->tdbmService->getObjects('photo', null, null, null, null, 'coiffuresenegal\Dao\Bean\PhotoBean');
	}
	
	/**
	 * Get coiffuresenegal\Dao\Bean\PhotoBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return coiffuresenegal\Dao\Bean\PhotoBean
	 * @throws TDBMException
	 */
	public function getById($id, $lazyLoading = false) {
		return $this->tdbmService->getObject('photo', $id, 'coiffuresenegal\Dao\Bean\PhotoBean', $lazyLoading);
	}
	
	/**
	 * Deletes the coiffuresenegal\Dao\Bean\PhotoBean passed in parameter.
	 *
	 * @param coiffuresenegal\Dao\Bean\PhotoBean $obj
	 */
	public function delete($obj) {
		$this->tdbmService->deleteObject($obj);
	}
	
	/**
	 * Get a list of coiffuresenegal\Dao\Bean\PhotoBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<coiffuresenegal\Dao\Bean\PhotoBean>
	 */
	protected function getListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		return $this->tdbmService->getObjects('photo', $filterBag, $orderbyBag, $from, $limit, 'coiffuresenegal\Dao\Bean\PhotoBean');
	}

	/**
	 * Get a single coiffuresenegal\Dao\Bean\PhotoBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return coiffuresenegal\Dao\Bean\PhotoBean
	 */
	protected function getByFilter($filterBag=null) {
		return $this->tdbmService->getObject('photo', $filterBag, 'coiffuresenegal\Dao\Bean\PhotoBean');
	}
	

	/**
	 * Return a new instance of coiffuresenegal\Dao\Bean\PhotoBean object, that will be persisted in database.
	 *
	 * @return coiffuresenegal\Dao\Bean\PhotoBean
	 */
	public function getNewPhoto() {
		return $this->create();
	}

	/**
	 * Persist the coiffuresenegal\Dao\Bean\PhotoBean instance
	 * (old function to keep compatibility with TDBM < 2.3)
	 *
	 */
	public function savePhoto($obj) {
		$this->save($obj);
	}
	
	/**
	 * Get all Photo records. 
	 *
	 * @return array<coiffuresenegal\Dao\Bean\PhotoBean>
	 */
	public function getPhotoList() {
		return $this->getList();
	}
	
	/**
	 * Get coiffuresenegal\Dao\Bean\PhotoBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return coiffuresenegal\Dao\Bean\PhotoBean
	 * @throws TDBMException
	 */
	public function getPhotoById($id, $lazyLoading = false) {
		return $this->getById($id, $lazyLoading);
	}
	
	/**
	 * Deletes the coiffuresenegal\Dao\Bean\PhotoBean passed in parameter.
	 *
	 * @param coiffuresenegal\Dao\Bean\PhotoBean $obj
	 */
	public function deletePhoto($obj) {
		$this->delete($obj);
	}
	
	/**
	 * Get a list of coiffuresenegal\Dao\Bean\PhotoBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<coiffuresenegal\Dao\Bean\PhotoBean>
	 */
	protected function getPhotoListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		return $this->getListByFilter($filterBag, $orderbyBag, $from, $limit);
	}

	/**
	 * Get a single coiffuresenegal\Dao\Bean\PhotoBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return coiffuresenegal\Dao\Bean\PhotoBean
	 */
	protected function getPhotoByFilter($filterBag=null) {
		return $this->getByFilter($filterBag);
	}
	
}
?>