<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The PhotoDao class will maintain the persistance of coiffuresenegal\Dao\Bean\PhotoBean class into the photo table.
 *
 * @Component
 * @dbTable photo
 */
class PhotoDao extends PhotoDaoBase
{

}