<?php

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the RegionDao class instead!
 */

namespace coiffuresenegal\Dao;

use Database\TDBM\TDBMService;


/**
 * The RegionDaoBase class will maintain the persistance of coiffuresenegal\Dao\Bean\RegionBean class into the region table.
 * 
 */
class RegionDaoBase extends DaoCommon implements DAOInterface {

    public $tableName = "region";
    public $tablePrimaryKey = "id_region";
    public $tableColumns = array(
        'id_region',
        'nom_region',
        'image',
        'banniere',
        'notice',
        'presentation',
        'position',
        'actif',
        'tag',
        'created_at',
        'updated_at'
    );

    /**
     * @var TDBMService
     */
    protected $tdbmService;

    public function __construct() {
        $this->setTdbmService(new TDBMService());
    }
    
    /**
     * Sets the TDBM service used by this DAO.
     *
     * @Property
     * @Compulsory
     * @param TDBMService $tdbmService
     */
    public function setTdbmService(TDBMService $tdbmService) {
        $this->tdbmService = $tdbmService;
    }
    
    /**
	 * Return a new instance of coiffuresenegal\Dao\Bean\RegionBean object, that will be persisted in database.
	 *
	 * @return coiffuresenegal\Dao\Bean\RegionBean
	 */
	public function create() {
		return $this->tdbmService->getNewObject('region', true, 'coiffuresenegal\Dao\Bean\RegionBean');
	}
	
	/**
	 * Persist the coiffuresenegal\Dao\Bean\RegionBean instance
	 *
	 */
	public function save($obj) {
		$obj->save();
	}

	/**
	 * Get all Region records. 
	 *
	 * @return array<coiffuresenegal\Dao\Bean\RegionBean>
	 */
	public function getList() {
		return $this->tdbmService->getObjects('region', null, null, null, null, 'coiffuresenegal\Dao\Bean\RegionBean');
	}
	
	/**
	 * Get coiffuresenegal\Dao\Bean\RegionBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return coiffuresenegal\Dao\Bean\RegionBean
	 * @throws TDBMException
	 */
	public function getById($id, $lazyLoading = false) {
		return $this->tdbmService->getObject('region', $id, 'coiffuresenegal\Dao\Bean\RegionBean', $lazyLoading);
	}
	
	/**
	 * Deletes the coiffuresenegal\Dao\Bean\RegionBean passed in parameter.
	 *
	 * @param coiffuresenegal\Dao\Bean\RegionBean $obj
	 */
	public function delete($obj) {
		$this->tdbmService->deleteObject($obj);
	}
	
	/**
	 * Get a list of coiffuresenegal\Dao\Bean\RegionBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<coiffuresenegal\Dao\Bean\RegionBean>
	 */
	protected function getListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		return $this->tdbmService->getObjects('region', $filterBag, $orderbyBag, $from, $limit, 'coiffuresenegal\Dao\Bean\RegionBean');
	}

	/**
	 * Get a single coiffuresenegal\Dao\Bean\RegionBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return coiffuresenegal\Dao\Bean\RegionBean
	 */
	protected function getByFilter($filterBag=null) {
		return $this->tdbmService->getObject('region', $filterBag, 'coiffuresenegal\Dao\Bean\RegionBean');
	}
	

	/**
	 * Return a new instance of coiffuresenegal\Dao\Bean\RegionBean object, that will be persisted in database.
	 *
	 * @return coiffuresenegal\Dao\Bean\RegionBean
	 */
	public function getNewRegion() {
		return $this->create();
	}

	/**
	 * Persist the coiffuresenegal\Dao\Bean\RegionBean instance
	 * (old function to keep compatibility with TDBM < 2.3)
	 *
	 */
	public function saveRegion($obj) {
		$this->save($obj);
	}
	
	/**
	 * Get all Region records. 
	 *
	 * @return array<coiffuresenegal\Dao\Bean\RegionBean>
	 */
	public function getRegionList() {
		return $this->getList();
	}
	
	/**
	 * Get coiffuresenegal\Dao\Bean\RegionBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return coiffuresenegal\Dao\Bean\RegionBean
	 * @throws TDBMException
	 */
	public function getRegionById($id, $lazyLoading = false) {
		return $this->getById($id, $lazyLoading);
	}
	
	/**
	 * Deletes the coiffuresenegal\Dao\Bean\RegionBean passed in parameter.
	 *
	 * @param coiffuresenegal\Dao\Bean\RegionBean $obj
	 */
	public function deleteRegion($obj) {
		$this->delete($obj);
	}
	
	/**
	 * Get a list of coiffuresenegal\Dao\Bean\RegionBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<coiffuresenegal\Dao\Bean\RegionBean>
	 */
	protected function getRegionListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		return $this->getListByFilter($filterBag, $orderbyBag, $from, $limit);
	}

	/**
	 * Get a single coiffuresenegal\Dao\Bean\RegionBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return coiffuresenegal\Dao\Bean\RegionBean
	 */
	protected function getRegionByFilter($filterBag=null) {
		return $this->getByFilter($filterBag);
	}
	
}
?>