<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The RegionDao class will maintain the persistance of coiffuresenegal\Dao\Bean\RegionBean class into the region table.
 *
 * @Component
 * @dbTable region
 */
class RegionDao extends RegionDaoBase
{
    /**
     * 
     * @param type $offset
     * @param type $limit
     * @param type $orderbyBag
     * @return type
     */
    public function getRegionWithPager($offset = null, $limit = null, $orderbyBag = null) {
    	return $this->getRegionListByFilter($orderbyBag, $offset, $limit);
    }
}