<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The SalonUneRegionDao class will maintain the persistance of coiffuresenegal\Dao\Bean\SalonUneRegionBean class into the salon_une_region table.
 *
 * @Component
 * @dbTable salon_une_region
 */
class SalonUneRegionDao extends SalonUneRegionDaoBase
{

}