<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The SalonDao class will maintain the persistance of coiffuresenegal\Dao\Bean\SalonBean class into the salon table.
 *
 * @Component
 * @dbTable salon
 */
class SalonDao extends SalonDaoBase
{

}