<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The SalonUneVilleDao class will maintain the persistance of coiffuresenegal\Dao\Bean\SalonUneVilleBean class into the salon_une_ville table.
 *
 * @Component
 * @dbTable salon_une_ville
 */
class SalonUneVilleDao extends SalonUneVilleDaoBase
{

}