<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The UserAdminDao class will maintain the persistance of coiffuresenegal\Dao\Bean\UserAdminBean class into the user_admin table.
 *
 * @Component
 * @dbTable user_admin
 */
class UserAdminDao extends UserAdminDaoBase
{

}