<?php

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the UserAdminDao class instead!
 */

namespace coiffuresenegal\Dao;

use Database\TDBM\TDBMService;

/**
 * The UserAdminDaoBase class will maintain the persistance of coiffuresenegal\Dao\Bean\UserAdminBean class into the user_admin table.
 * 
 */
class UserAdminDaoBase extends DaoCommon implements DAOInterface {

    public $tableName = "user_admin";
    public $tablePrimaryKey = "ID_user_admin";
    public $tableColumns = array(
        'ID_user_admin',
        'user_nom',
        'user_login',
        'user_password',
        'est_administrateur',
        'est_client',
        'created_at',
        'updated_at'
    );
    
    
    /**
     * @var TDBMService
     */
    protected $tdbmService;

    public function __construct() {
        $this->setTdbmService(new TDBMService());
    }
    
    /**
     * Sets the TDBM service used by this DAO.
     *
     * @Property
     * @Compulsory
     * @param TDBMService $tdbmService
     */
    public function setTdbmService(TDBMService $tdbmService) {
        $this->tdbmService = $tdbmService;
    }
    

    /**
	 * Return a new instance of coiffuresenegal\Dao\Bean\UserAdminBean object, that will be persisted in database.
	 *
	 * @return coiffuresenegal\Dao\Bean\UserAdminBean
	 */
	public function create() {
		return $this->tdbmService->getNewObject('user_admin', true, 'coiffuresenegal\Dao\Bean\UserAdminBean');
	}
	
	/**
	 * Persist the coiffuresenegal\Dao\Bean\UserAdminBean instance
	 *
	 */
	public function save($obj) {
		$obj->save();
	}

	/**
	 * Get all UserAdmin records. 
	 *
	 * @return array<coiffuresenegal\Dao\Bean\UserAdminBean>
	 */
	public function getList() {
		return $this->tdbmService->getObjects('user_admin', null, null, null, null, 'coiffuresenegal\Dao\Bean\UserAdminBean');
	}
	
	/**
	 * Get coiffuresenegal\Dao\Bean\UserAdminBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return coiffuresenegal\Dao\Bean\UserAdminBean
	 * @throws TDBMException
	 */
	public function getById($id, $lazyLoading = false) {
		return $this->tdbmService->getObject('user_admin', $id, 'coiffuresenegal\Dao\Bean\UserAdminBean', $lazyLoading);
	}
	
	/**
	 * Deletes the coiffuresenegal\Dao\Bean\UserAdminBean passed in parameter.
	 *
	 * @param coiffuresenegal\Dao\Bean\UserAdminBean $obj
	 */
	public function delete($obj) {
		$this->tdbmService->deleteObject($obj);
	}
	
	/**
	 * Get a list of coiffuresenegal\Dao\Bean\UserAdminBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<coiffuresenegal\Dao\Bean\UserAdminBean>
	 */
	protected function getListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		return $this->tdbmService->getObjects('user_admin', $filterBag, $orderbyBag, $from, $limit, 'coiffuresenegal\Dao\Bean\UserAdminBean');
	}

	/**
	 * Get a single coiffuresenegal\Dao\Bean\UserAdminBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return coiffuresenegal\Dao\Bean\UserAdminBean
	 */
	protected function getByFilter($filterBag=null) {
		return $this->tdbmService->getObject('user_admin', $filterBag, 'coiffuresenegal\Dao\Bean\UserAdminBean');
	}
	

	/**
	 * Return a new instance of coiffuresenegal\Dao\Bean\UserAdminBean object, that will be persisted in database.
	 *
	 * @return coiffuresenegal\Dao\Bean\UserAdminBean
	 */
	public function getNewUserAdmin() {
		return $this->create();
	}

	/**
	 * Persist the coiffuresenegal\Dao\Bean\UserAdminBean instance
	 * (old function to keep compatibility with TDBM < 2.3)
	 *
	 */
	public function saveUserAdmin($obj) {
		$this->save($obj);
	}
	
	/**
	 * Get all UserAdmin records. 
	 *
	 * @return array<coiffuresenegal\Dao\Bean\UserAdminBean>
	 */
	public function getUserAdminList() {
		return $this->getList();
	}
	
	/**
	 * Get coiffuresenegal\Dao\Bean\UserAdminBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return coiffuresenegal\Dao\Bean\UserAdminBean
	 * @throws TDBMException
	 */
	public function getUserAdminById($id, $lazyLoading = false) {
		return $this->getById($id, $lazyLoading);
	}
	
	/**
	 * Deletes the coiffuresenegal\Dao\Bean\UserAdminBean passed in parameter.
	 *
	 * @param coiffuresenegal\Dao\Bean\UserAdminBean $obj
	 */
	public function deleteUserAdmin($obj) {
		$this->delete($obj);
	}
	
	/**
	 * Get a list of coiffuresenegal\Dao\Bean\UserAdminBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<coiffuresenegal\Dao\Bean\UserAdminBean>
	 */
	protected function getUserAdminListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		return $this->getListByFilter($filterBag, $orderbyBag, $from, $limit);
	}

	/**
	 * Get a single coiffuresenegal\Dao\Bean\UserAdminBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return coiffuresenegal\Dao\Bean\UserAdminBean
	 */
	protected function getUserAdminByFilter($filterBag=null) {
		return $this->getByFilter($filterBag);
	}
	
}
?>