<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace coiffuresenegal\Dao;

/**
 * The VilleDao class will maintain the persistance of coiffuresenegal\Dao\Bean\VilleBean class into the ville table.
 *
 * @Component
 * @dbTable ville
 */
class VilleDao extends VilleDaoBase
{

}