<?php

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the VilleDao class instead!
 */

namespace coiffuresenegal\Dao;

use Database\TDBM\TDBMService;

/**
 * The VilleDaoBase class will maintain the persistance of coiffuresenegal\Dao\Bean\VilleBean class into the ville table.
 * 
 */
class VilleDaoBase extends DaoCommon implements DAOInterface {

    public $tableName = "ville";
    public $tablePrimaryKey = "ID_ville";
    public $tableColumns = array(
        'ID_ville',
        'id_region',
        'nom_ville',
        'image',
        'banniere',
        'notice',
        'presentation',
        'position',
        'actif',
        'tag',
        'created_at',
        'updated_at'
    );
    
    /**
     * @var TDBMService
     */
    protected $tdbmService;

    public function __construct() {
        $this->setTdbmService(new TDBMService());
    }
    
    /**
     * Sets the TDBM service used by this DAO.
     *
     * @Property
     * @Compulsory
     * @param TDBMService $tdbmService
     */
    public function setTdbmService(TDBMService $tdbmService) {
        $this->tdbmService = $tdbmService;
    }

    /**
	 * Return a new instance of coiffuresenegal\Dao\Bean\VilleBean object, that will be persisted in database.
	 *
	 * @return coiffuresenegal\Dao\Bean\VilleBean
	 */
	public function create() {
		return $this->tdbmService->getNewObject('ville', true, 'coiffuresenegal\Dao\Bean\VilleBean');
	}
	
	/**
	 * Persist the coiffuresenegal\Dao\Bean\VilleBean instance
	 *
	 */
	public function save($obj) {
		$obj->save();
	}

	/**
	 * Get all Ville records. 
	 *
	 * @return array<coiffuresenegal\Dao\Bean\VilleBean>
	 */
	public function getList() {
		return $this->tdbmService->getObjects('ville', null, null, null, null, 'coiffuresenegal\Dao\Bean\VilleBean');
	}
	
	/**
	 * Get coiffuresenegal\Dao\Bean\VilleBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return coiffuresenegal\Dao\Bean\VilleBean
	 * @throws TDBMException
	 */
	public function getById($id, $lazyLoading = false) {
		return $this->tdbmService->getObject('ville', $id, 'coiffuresenegal\Dao\Bean\VilleBean', $lazyLoading);
	}
	
	/**
	 * Deletes the coiffuresenegal\Dao\Bean\VilleBean passed in parameter.
	 *
	 * @param coiffuresenegal\Dao\Bean\VilleBean $obj
	 */
	public function delete($obj) {
		$this->tdbmService->deleteObject($obj);
	}
	
	/**
	 * Get a list of coiffuresenegal\Dao\Bean\VilleBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<coiffuresenegal\Dao\Bean\VilleBean>
	 */
	protected function getListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		return $this->tdbmService->getObjects('ville', $filterBag, $orderbyBag, $from, $limit, 'coiffuresenegal\Dao\Bean\VilleBean');
	}

	/**
	 * Get a single coiffuresenegal\Dao\Bean\VilleBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return coiffuresenegal\Dao\Bean\VilleBean
	 */
	protected function getByFilter($filterBag=null) {
		return $this->tdbmService->getObject('ville', $filterBag, 'coiffuresenegal\Dao\Bean\VilleBean');
	}
	

	/**
	 * Return a new instance of coiffuresenegal\Dao\Bean\VilleBean object, that will be persisted in database.
	 *
	 * @return coiffuresenegal\Dao\Bean\VilleBean
	 */
	public function getNewVille() {
		return $this->create();
	}

	/**
	 * Persist the coiffuresenegal\Dao\Bean\VilleBean instance
	 * (old function to keep compatibility with TDBM < 2.3)
	 *
	 */
	public function saveVille($obj) {
		$this->save($obj);
	}
	
	/**
	 * Get all Ville records. 
	 *
	 * @return array<coiffuresenegal\Dao\Bean\VilleBean>
	 */
	public function getVilleList() {
		return $this->getList();
	}
	
	/**
	 * Get coiffuresenegal\Dao\Bean\VilleBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return coiffuresenegal\Dao\Bean\VilleBean
	 * @throws TDBMException
	 */
	public function getVilleById($id, $lazyLoading = false) {
		return $this->getById($id, $lazyLoading);
	}
	
	/**
	 * Deletes the coiffuresenegal\Dao\Bean\VilleBean passed in parameter.
	 *
	 * @param coiffuresenegal\Dao\Bean\VilleBean $obj
	 */
	public function deleteVille($obj) {
		$this->delete($obj);
	}
	
	/**
	 * Get a list of coiffuresenegal\Dao\Bean\VilleBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<coiffuresenegal\Dao\Bean\VilleBean>
	 */
	protected function getVilleListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		return $this->getListByFilter($filterBag, $orderbyBag, $from, $limit);
	}

	/**
	 * Get a single coiffuresenegal\Dao\Bean\VilleBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return coiffuresenegal\Dao\Bean\VilleBean
	 */
	protected function getVilleByFilter($filterBag=null) {
		return $this->getByFilter($filterBag);
	}
	
}
?>