<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Form;

use coiffuresenegal\Dao\ArticleDao;
use coiffuresenegal\Dao\ModeleArticleDao;
use coiffuresenegal\Dao\SalonDao;

/**
 * The ArticleDao class will maintain the persistance of coiffuresenegal\Dao\Bean\ArticleBean class into the article table.
 *
 * @Component
 * @dbTable article
 */
class ArticleForm extends Form {

    public $isModificationForm = false;

    /**
     * @var ArticleDao
     */
    public $articleDao;

    /**
     * @var ModeleArticleDao
     */
    public $modeleArticleDao;

    /**
     * @var SalonDao
     */
    public $salonDao;
    public $articleObject;

    function __construct($idArticle = null, $name = null, $method=null, $action=null, $onsubmit = null, $idArray = null) {
        $this->articleDao = new ArticleDao();
        $this->modeleArticleDao = new ModeleArticleDao();
        $this->salonDao = new SalonDao();

        if ($idArticle == null) {
            parent::__construct("create", $name, $method, $action, $onsubmit, null);

            /**
             * Construire la liste des modèles d'articles
             */
            $modeles = $this->modeleArticleDao->getList();
            $modeleArticleSelectList = array();
            foreach ($modeleArticleSelectList as $oneModeleArticle) {
                $idModeleArticle = $oneModeleArticle->getIdModele();
                $nomModeleArticle = $oneModeleArticle->getNomModele();
                $selectModeleArticle = false;
                
                array_push($modeleArticleSelectList, array($idModeleArticle, $nomModeleArticle, $selectModeleArticle));
            }
            
            
            
            /**
             * Construire la liste des salons
             */
            $salons = $this->salonDao->getList();
            $salonSelectList = array();
            foreach ($salonSelectList as $oneSalon) {
                $idSalon = $oneSalon->getIdSalon();
                $nomSalon = $oneSalon->getNomSalon();
                $selectSalon = false;
                
                array_push($salonSelectList, array('value' => $idSalon, 'label' => $nomSalon, 'selected' => $selectSalon));
            }
            
            $this->formFields = array(
                array("type" => "select", "name" => "id_modele", "value" => $modeleArticleSelectList, "label" => "Modèle d'article"),
                array("type" => "select", "name" => "id_salon", "value" => $salonSelectList, "label" => "Salon"),
                array("type" => "text", "name" => "titre_article", "value" => "", "label" => "Titre"),
                array("type" => "file", "name" => "image", "value" => "", "label" => "Image"),
                array("type" => "textarea", "name" => "notice", "value" => "", "label" => "Résumé"),
                array("type" => "boolean", "name" => "actif", "value" => "true", "label" => "Publier ?"),
                array("type" => "boolean", "name" => "article_une", "value" => "true", "label" => "Une ?")
            );
            
        } else {
            $this->isModificationForm = true;
            parent::__construct("modify", $name, $method, $action, $onsubmit, array('id_article', $idArticle));

            $this->articleObject = $this->articleDao->getById($idArticle);

            /**
             * Construire la liste des modèles d'articles
             */
            $modeles = $this->modeleArticleDao->getList();
            $modeleArticleSelectList = array();
            foreach ($modeleArticleSelectList as $oneModeleArticle) {
                $idModeleArticle = $oneModeleArticle->getIdModele();
                $nomModeleArticle = $oneModeleArticle->getNomModele();
                $selectModeleArticle = false;
                
                if($idModeleArticle == $this->articleObject->getIdModele()) $selectModeleArticle = true;
                
                array_push($modeleArticleSelectList, array($idModeleArticle, $nomModeleArticle, $selectModeleArticle));
            }
            
            
            
            /**
             * Construire la liste des salons
             */
            $salons = $this->salonDao->getList();
            $salonSelectList = array();
            foreach ($salonSelectList as $oneSalon) {
                $idSalon = $oneSalon->getIdSalon();
                $nomSalon = $oneSalon->getNomSalon();
                $selectSalon = false;
                
                if($idSalon == $this->articleObject->getIdSalon()) $selectSalon = true;
                
                array_push($salonSelectList, array('value' => $idSalon, 'label' => $nomSalon, 'selected' => $selectSalon));
            }
            
            $this->formFields = array(
                array("type" => "select", "name" => "id_modele", "value" => $modeleArticleSelectList, "label" => "Modèle d'article"),
                array("type" => "select", "name" => "id_salon", "value" => $salonSelectList, "label" => "Salon"),
                array("type" => "text", "name" => "titre_article", "value" => $this->articleObject->getTitreArticle(), "label" => "Titre"),
                array("type" => "file", "name" => "image", "value" => $this->articleObject->getImage(), "label" => "Image"),
                array("type" => "textarea", "name" => "notice", "value" => $this->articleObject->getNotice(), "label" => "Résumé"),
                array("type" => "boolean", "name" => "actif", "value" => $this->articleObject->getActif(), "label" => "Publier ?"),
                array("type" => "boolean", "name" => "article_une", "value" => $this->articleObject->getArticleUne(), "label" => "Une ?")
            );
        }
    }

}