<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Form;

/**
 * The ArticleDao class will maintain the persistance of coiffuresenegal\Dao\Bean\ArticleBean class into the article table.
 *
 * @Component
 * @dbTable article
 */
class Form {

    public $formName;
    public $formMethod;
    public $formAction;
    public $formOnSubmit;
    public $formType;
    public $htmlHeader;
    public $htmlContent;
    public $htmlFooter = "";
    public $formFields;

    function __construct($type = "create", $name = null, $method=null, $action=null, $onsubmit = null, $idArray = null) {
        if ($name != null)
            $this->formName = $name;
        else
            $this->formName = "";


        if ($method != null)
            $this->formMethod = $method;
        else
            $this->formMethod = "POST";


        if ($action != null)
            $this->formAction = $action;
        else
            $this->formAction = "";


        if ($onsubmit != null)
            $this->formOnSubmit = $onsubmit;
        else
            $this->formOnSubmit = "";

        $this->htmlHeader = "<form name='" . $this->formName . "' action='" . $this->formAction . "' onsubmit='" . $this->formOnSubmit . "' method='" . $this->formMethod . "' class='form-horizontal' acceptcharset='' enctype='application/x-www-form-urlencoded'>";
        $this->htmlHeader .= "<table cellpadding=3 cellspacing=3>";

        $this->htmlContent = "";

        switch ($type) {
            case "modify":
                $this->htmlContent .= "<tr class='form_tr'>";
                $this->htmlContent .= "<td colspan=2>";
                $this->htmlContent .= "<input type='hidden' name='" . $idArray[0] . "' value='" . $idArray[1] . "' />";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "</tr>";
                break;
            default: //create
                break;
        }
        
        $this->htmlFooter .= "<tr class='form_tr'>";
        $this->htmlFooter .= "<td colspan=2>";
        $this->htmlFooter .= "<div class='form-actions'>";
        $this->htmlFooter .= "<button class='btn btn-primary' type='submit'>Enregistrer</button>";
        $this->htmlFooter .= "<button class='btn' type='reset'>Annuler les modifications</button>";
        $this->htmlFooter .= "</div>";
        $this->htmlFooter .= "</td>";
        $this->htmlFooter .= "</tr>";
                
        $this->htmlFooter .= "</table>";
        $this->htmlFooter .= "</form>";
    }

    public function addField($type, $name, $value, $label) {
        /**
         * $this->formFields = array(
          array("type" => "select", "name" => "id_modele", "value" => $modeleArticleSelectList, "label" => "Modèle d'article"),
          array("type" => "select", "name" => "id_salon", "value" => $salonSelectList, "label" => "Salon"),
          array("type" => "text", "name" => "titre_article", "value" => "", "label" => "Titre"),
          array("type" => "file", "name" => "image", "value" => "", "label" => "Image"),
          array("type" => "textarea", "name" => "notice", "value" => "", "label" => "Résumé"),
          array("type" => "boolean", "name" => "actif", "value" => "true", "label" => "Publier ?"),
          array("type" => "boolean", "name" => "article_une", "value" => "true", "label" => "Une ?")
          );
         */
        switch ($type) {
            case "text":
                $this->htmlContent .= "<tr class='form_tr'>";
                $this->htmlContent .= "<td class='form_td_label'>";
                        $this->htmlContent .= "<div class='control-group'>";
                            $this->htmlContent .= "<label for='" .$name. "' class='control-label'>";
                                $this->htmlContent .= $label;
                            $this->htmlContent .= "</label>";
                        $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "<td class='form_td_field'>";
                        $this->htmlContent .= "<div class='controls'>";
                            $this->htmlContent .= "<input type='text' name='" . $name . "' value='" . $value . "' />";
                        $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "</tr>";

                break;

            case "select":
                $this->htmlContent .= "<tr class='form_tr'>";
                $this->htmlContent .= "<td class='form_td_label'>";
                    $this->htmlContent .= "<div class='control-group'>";
                        $this->htmlContent .= "<label for='" .$name. "' class='control-label'>";
                            $this->htmlContent .= $label;
                        $this->htmlContent .= "</label>";
                    $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "<td class='form_td_field'>";
                        $this->htmlContent .= "<div class='controls'>";
                            $this->htmlContent .= "<select name='" . $name . "'>";

                            foreach ($value as $oneSelectListValue) {
                                /**
                                 * value, label, selected
                                 */
                                $this->htmlContent .= "<option value='" . $oneSelectListValue['value'] . "'";
                                if ($oneSelectListValue['selected'])
                                    $this->htmlContent .= " selected='selected'";
                                $this->htmlContent .= ">" . $oneSelectListValue['label'] . "</option>";
                            }

                            $this->htmlContent .= "</select>";
                        $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "</tr>";

                break;
            case "file":
                $this->htmlContent .= "<tr class='form_tr'>";
                $this->htmlContent .= "<td class='form_td_label'>";
                    $this->htmlContent .= "<div class='control-group'>";
                        $this->htmlContent .= "<label for='" .$name. "' class='control-label'>";
                            $this->htmlContent .= $label;
                        $this->htmlContent .= "</label>";

                    $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "<td class='form_td_field'>";
                        $this->htmlContent .= "<div class='controls'>";
                            $this->htmlContent .= "<input type='file' name='" . $name . "' />";
                        $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "</tr>";

                break;
            
            case "textarea":
                $this->htmlContent .= "<tr class='form_tr'>";
                $this->htmlContent .= "<td class='form_td_label'>";
                    $this->htmlContent .= "<div class='control-group'>";
                        $this->htmlContent .= "<label for='" .$name. "' class='control-label'>";
                            $this->htmlContent .= $label;
                        $this->htmlContent .= "</label>";
                    $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "<td class='form_td_field'>";
                        $this->htmlContent .= "<div class='controls'>";
                            $this->htmlContent .= "<textarea name='" . $name . "'>" . $value . "</textarea>";
                        $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "</tr>";

                break;
            
            case "boolean":
                $this->htmlContent .= "<tr class='form_tr'>";
                $this->htmlContent .= "<td class='form_td_label'>";
                    $this->htmlContent .= "<div class='control-group'>";
                        $this->htmlContent .= "<label for='" .$name. "' class='control-label'>";
                            $this->htmlContent .= $label;
                        $this->htmlContent .= "</label>";
                    $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "<td class='form_td_field'>";
                        $this->htmlContent .= "<div class='controls'>";
                            $this->htmlContent .= "<input type='checkbox' name='" . $name . "' value='1'";
                                if ($value == 1 || $value == true)
                                        $this->htmlContent .= " checked='checked'";
                                $this->htmlContent .= " />";
                        $this->htmlContent .= "</div>";
                $this->htmlContent .= "</td>";
                $this->htmlContent .= "</tr>";

                break;

            default:
                break;
        }
    }

    public function toHtml() {
        foreach ($this->formFields as $oneFormField) {
            $this->addField($oneFormField['type'], $oneFormField['name'], $oneFormField['value'], $oneFormField['label']);
        }

        return $this->htmlHeader . $this->htmlContent . $this->htmlFooter;
    }

}