<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace coiffuresenegal\Form;

use coiffuresenegal\Dao\RegionDao;

/**
 * The RegionDao class will maintain the persistance of coiffuresenegal\Dao\Bean\RegionBean class into the region table.
 *
 * @Component
 * @dbTable region
 */
class RegionForm extends Form {

    public $isModificationForm = false;

    /**
     * @var RegionDao
     */
    public $regionDao;

    public $regionObject;

    function __construct($idRegion = null, $name = null, $method=null, $action=null, $onsubmit = null, $idArray = null) {
        $this->regionDao = new RegionDao();

        if ($idRegion == null) {
            parent::__construct("create", $name, $method, $action, $onsubmit, null);
            
                    
            $this->formFields = array(
                array("type" => "text", "name" => "nom_region", "value" => "", "label" => "Nom de la région"),
                array("type" => "file", "name" => "image", "value" => "", "label" => "Image"),
                array("type" => "file", "name" => "banniere", "value" => "", "label" => "Bannière"),
                array("type" => "textarea", "name" => "notice", "value" => "", "label" => "Résumé"),
                array("type" => "textarea", "name" => "presentation", "value" => "", "label" => "Présentation"),
                array("type" => "text", "name" => "tag", "value" => "", "label" => "Tag"),
                array("type" => "integer", "name" => "position", "value" => "", "label" => "Position"),
                array("type" => "boolean", "name" => "actif", "value" => "true", "label" => "Activer ?")
            );
            
        } else {
            $this->isModificationForm = true;
            parent::__construct("modify", $name, $method, $action, $onsubmit, array('id_region', $idRegion));

            $this->regionObject = $this->regionDao->getById($idRegion);

            
            
            $this->formFields = array(
                array("type" => "text", "name" => "nom_region", "value" => $this->regionObject->getNomRegion(), "label" => "Nom de la région"),
                array("type" => "file", "name" => "image", "value" => $this->regionObject->getImage(), "label" => "Image"),
                array("type" => "file", "name" => "banniere", "value" => $this->regionObject->getBanniere(), "label" => "Bannière"),
                array("type" => "textarea", "name" => "notice", "value" => $this->regionObject->getNotice(), "label" => "Résumé"),
                array("type" => "textarea", "name" => "presentation", "value" => $this->regionObject->getPresentation(), "label" => "Présentation"),
                array("type" => "text", "name" => "tag", "value" => $this->regionObject->getTag(), "label" => "Tag"),
                array("type" => "text", "name" => "position", "value" => $this->regionObject->getPosition(), "label" => "Position"),
                array("type" => "boolean", "name" => "actif", "value" => $this->regionObject->getActif(), "label" => "Activer ?")
            );
        }
    }
    
    
    public function saveRegion($postValues, $fileValues) {
        if($this->isModificationForm)
            $regionObject = $this->regionDao->getById($postValues['id_region']);
        else
            $regionObject = $this->regionDao->getNewRegion();
        
        return parent::save($this->formFields, $postValues, $fileValues, $this->regionDao, $regionObject, "/images/regions/");
        
    }

}